ros2pix4d:
  topics:
    gps: "/vectornav/GPS"
    # gps: "/zedf9p/LLA_zedf9p"
    imu: "/vectornav/IMU"
    cam: /dfm27uro135ml/cam/image_raw

  rosbag:
    # path: "/home/johanavila/avila_ws/src"
    path: "/home/avila/avila_ws/src"
    name: "lote_2_nataima_arroz_2022-10-03-09-32-17"

  img:
    format: "jpg"
